[package]
name = "terminal-play"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
ctrlc = "3.2.3"
chrono = "0.4.22"
clap = { version = "4.0.18", features = ["derive"] }
rodio = "0.16.0"
